#!/bin/bash

# Check if a domain name was provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 YourDomainName.com"
    exit 1
fi

DOMAIN=$1
WEB_DIR="/var/www/$DOMAIN"
DBNAME="website_${DOMAIN//./_}"
DBUSER=$(grep DB_USER credentials.txt | cut -d '=' -f 2-)
DBPASS=$(grep DB_PASS credentials.txt | cut -d '=' -f 2-)

echo "You are trying to Delete the website files, and DataBase for $DOMAIN this action is not reversable."
echo "Make sure if you take the backup for $DOMAIN"
read -p "Are you sure do you want to Continue and Delete the website files, and DataBase for $DOMAIN? (yes/no): " undo_website_setup

if [ "$undo_website_setup" == "yes" || "$undo_website_setup" == "y" ]; then
	# Check if the domain has a Let's Encrypt certificate
	if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
		read -p "Do you want to revoke the SSL certificate for $DOMAIN? (yes/no): " revoke_response

		if [ "$revoke_response" == "yes" ]; then
			sudo certbot delete --cert-name $DOMAIN
		fi
	fi

	# Remove from /etc/hosts
	sudo sed -i "/$DOMAIN/d" /etc/hosts

	# Remove Apache SSL configuration generated by Let's Encrypt
	if [ -f "/etc/httpd/conf.d/${DOMAIN}-le-ssl.conf" ]; then
		sudo rm "/etc/httpd/conf.d/${DOMAIN}-le-ssl.conf"
		sudo systemctl reload httpd
	fi

	# Delete MySQL database
	mysql -u $DBUSER -p$DBPASS -e "DROP DATABASE $DBNAME;"

	# Disable and delete Apache configuration
	if [ -f "/etc/httpd/conf.d/$DOMAIN.conf" ]; then
		sudo rm "/etc/httpd/conf.d/$DOMAIN.conf"
		sudo systemctl reload httpd
	fi

	# Delete WordPress files
	if [ -d "$WEB_DIR" ]; then
		sudo rm -rf $WEB_DIR
	fi

	echo "Reversal complete. Please check to ensure everything was cleaned up properly."

else 

	echo "Reversal not started and operation Aborted."

fi
